update=Mon 08 Jun 2015 15:59:31 EEST
last_client=eeschema
[eeschema]
version=1
LibDir=
NetFmtName=
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=power
LibName2=conn
LibName3=linear
LibName4=memory
LibName5=audio
LibName6=device
LibName7=transistors
LibName8=/home/mark/Projects/marks-kicad-library/mark
